// Sector / sub-sector taxonomy for the Intake form (/new). Two mandatory
// dropdowns instead of the free-text field the original spec called for —
// an explicit product decision (2026-09-03) to know exactly what kind of
// business each respondent runs, at the cost of maintaining this list.
// Stored value is a plain English string ("Sector — Sub-sector"), same
// storage shape as before (Intake.sector / Business.sector are unchanged,
// still `sector: string`) — only the input UI changed, not the schema.
//
// 40 top-level sectors, ~460 sub-sectors, translated into all 5 UI languages.
// Generated once from a fixed English taxonomy; ids are stable kebab/snake_case
// slugs derived from the English name, de-duplicated where two sub-sectors in
// different groups would otherwise collide is not needed since ids are scoped
// per-group by lookup, but each group's own id is globally unique.

import type { Language } from "./types";

export type Row = Record<Language, string>;
const row = (en: string, uz: string, ru: string, zh: string, fr: string): Row => ({ en, uz, ru, zh, fr });

export interface SubSector {
  id: string;
  name: Row;
}
export interface SectorGroup {
  id: string;
  name: Row;
  subsectors: SubSector[];
}

export const SECTOR_TAXONOMY: SectorGroup[] = [
  {
    id: "agriculture_food_and_agribusiness",
    name: row("Agriculture, Food & Agribusiness", "Qishloq xoʻjaligi, oziq-ovqat va agrobiznes", "Сельское хозяйство, продовольствие и агробизнес", "农业、食品与农业综合企业", "Agriculture, alimentation et agroalimentaire"),
    subsectors: [
      { id: "crop_farming", name: row("Crop Farming", "Dehqonchilik", "Растениеводство", "农作物种植", "Culture agricole") },
      { id: "livestock", name: row("Livestock", "Chorvachilik", "Животноводство", "畜牧业", "Élevage") },
      { id: "fisheries_and_aquaculture", name: row("Fisheries & Aquaculture", "Baliqchilik va akvakultura", "Рыболовство и аквакультура", "渔业与水产养殖", "Pêche et aquaculture") },
      { id: "forestry_and_timber", name: row("Forestry & Timber", "Oʻrmon xoʻjaligi va yogʻochsozlik", "Лесное хозяйство и лесоматериалы", "林业与木材", "Foresterie et bois") },
      { id: "agricultural_services", name: row("Agricultural Services", "Qishloq xoʻjaligi xizmatlari", "Сельскохозяйственные услуги", "农业服务", "Services agricoles") },
      { id: "agricultural_technology", name: row("Agricultural Technology", "Qishloq xoʻjaligi texnologiyalari", "Агротехнологии", "农业技术", "Technologie agricole") },
      { id: "food_processing", name: row("Food Processing", "Oziq-ovqatni qayta ishlash", "Пищевая переработка", "食品加工", "Transformation alimentaire") },
      { id: "food_and_beverage_manufacturing", name: row("Food & Beverage Manufacturing", "Oziq-ovqat va ichimliklar ishlab chiqarish", "Производство продуктов питания и напитков", "食品饮料制造", "Fabrication de produits alimentaires et boissons") },
      { id: "food_distribution", name: row("Food Distribution", "Oziq-ovqat mahsulotlarini tarqatish", "Дистрибуция продуктов питания", "食品分销", "Distribution alimentaire") },
      { id: "food_retail", name: row("Food Retail", "Oziq-ovqat chakana savdosi", "Розничная торговля продуктами питания", "食品零售", "Commerce de détail alimentaire") },
      { id: "restaurants_and_food_services", name: row("Restaurants & Food Services", "Restoranlar va ovqatlanish xizmatlari", "Рестораны и предприятия питания", "餐厅与餐饮服务", "Restaurants et services de restauration") },
    ],
  },
  {
    id: "mining_minerals_and_natural_resources",
    name: row("Mining, Minerals & Natural Resources", "Kon-metallurgiya, minerallar va tabiiy resurslar", "Горнодобыча, полезные ископаемые и природные ресурсы", "矿业、矿产与自然资源", "Mines, minéraux et ressources naturelles"),
    subsectors: [
      { id: "oil_and_gas", name: row("Oil & Gas", "Neft va gaz", "Нефть и газ", "石油天然气", "Pétrole et gaz") },
      { id: "coal", name: row("Coal", "Koʻmir", "Уголь", "煤炭", "Charbon") },
      { id: "metals_and_mining", name: row("Metals & Mining", "Metallar va kon-qazib olish", "Металлы и горнодобыча", "金属与采矿", "Métaux et exploitation minière") },
      { id: "precious_metals", name: row("Precious Metals", "Qimmatbaho metallar", "Драгоценные металлы", "贵金属", "Métaux précieux") },
      { id: "critical_minerals", name: row("Critical Minerals", "Muhim minerallar", "Критически важные полезные ископаемые", "关键矿产", "Minéraux critiques") },
      { id: "industrial_minerals", name: row("Industrial Minerals", "Sanoat minerallari", "Промышленные минералы", "工业矿产", "Minéraux industriels") },
      { id: "quarrying", name: row("Quarrying", "Karerchilik", "Карьерная добыча", "采石业", "Carrières") },
      { id: "mining_services", name: row("Mining Services", "Kon-qazib olish xizmatlari", "Горнодобывающие услуги", "采矿服务", "Services miniers") },
      { id: "mining_equipment_and_technology", name: row("Mining Equipment & Technology", "Kon-qazib olish uskunalari va texnologiyalari", "Горнодобывающее оборудование и технологии", "采矿设备与技术", "Équipement et technologie minière") },
      { id: "mineral_processing", name: row("Mineral Processing", "Minerallarni qayta ishlash", "Переработка полезных ископаемых", "矿产加工", "Traitement des minéraux") },
    ],
  },
  {
    id: "energy_and_power",
    name: row("Energy & Power", "Energetika va elektr taʼminoti", "Энергетика и электроэнергия", "能源与电力", "Énergie et électricité"),
    subsectors: [
      { id: "oil_and_gas_energy", name: row("Oil & Gas Energy", "Neft-gaz energetikasi", "Нефтегазовая энергетика", "石油天然气能源", "Énergie pétrolière et gazière") },
      { id: "electricity_generation", name: row("Electricity Generation", "Elektr energiyasi ishlab chiqarish", "Производство электроэнергии", "电力生产", "Production d'électricité") },
      { id: "electricity_transmission_and_distribution", name: row("Electricity Transmission & Distribution", "Elektr energiyasini uzatish va taqsimlash", "Передача и распределение электроэнергии", "输配电", "Transport et distribution d'électricité") },
      { id: "solar_energy", name: row("Solar Energy", "Quyosh energiyasi", "Солнечная энергия", "太阳能", "Énergie solaire") },
      { id: "wind_energy", name: row("Wind Energy", "Shamol energiyasi", "Ветровая энергия", "风能", "Énergie éolienne") },
      { id: "hydropower", name: row("Hydropower", "Gidroenergetika", "Гидроэнергетика", "水电", "Hydroélectricité") },
      { id: "nuclear_energy", name: row("Nuclear Energy", "Yadro energetikasi", "Атомная энергетика", "核能", "Énergie nucléaire") },
      { id: "geothermal_energy", name: row("Geothermal Energy", "Geotermal energiya", "Геотермальная энергия", "地热能", "Énergie géothermique") },
      { id: "bioenergy", name: row("Bioenergy", "Bioenergiya", "Биоэнергетика", "生物能源", "Bioénergie") },
      { id: "hydrogen_energy", name: row("Hydrogen Energy", "Vodorod energetikasi", "Водородная энергетика", "氢能", "Énergie hydrogène") },
      { id: "energy_storage", name: row("Energy Storage", "Energiya saqlash", "Накопление энергии", "储能", "Stockage d'énergie") },
      { id: "energy_efficiency", name: row("Energy Efficiency", "Energiya samaradorligi", "Энергоэффективность", "能效", "Efficacité énergétique") },
      { id: "energy_technology_and_services", name: row("Energy Technology & Services", "Energetika texnologiyalari va xizmatlari", "Энергетические технологии и услуги", "能源技术与服务", "Technologies et services énergétiques") },
    ],
  },
  {
    id: "utilities_and_essential_infrastructure",
    name: row("Utilities & Essential Infrastructure", "Kommunal xizmatlar va hayotiy zaruriy infratuzilma", "Коммунальные услуги и базовая инфраструктура", "公用事业与基础设施", "Services publics et infrastructures essentielles"),
    subsectors: [
      { id: "water_utilities", name: row("Water Utilities", "Suv taʼminoti xizmatlari", "Водоснабжение", "供水事业", "Services des eaux") },
      { id: "wastewater_services", name: row("Wastewater Services", "Oqova suvlar xizmatlari", "Услуги водоотведения", "污水处理服务", "Services d'assainissement") },
      { id: "waste_management", name: row("Waste Management", "Chiqindilarni boshqarish", "Управление отходами", "废物管理", "Gestion des déchets") },
      { id: "recycling", name: row("Recycling", "Qayta ishlash (retsikling)", "Переработка отходов", "回收利用", "Recyclage") },
      { id: "electricity_utilities", name: row("Electricity Utilities", "Elektr taʼminoti xizmatlari", "Электроснабжение", "供电事业", "Services d'électricité") },
      { id: "gas_utilities", name: row("Gas Utilities", "Gaz taʼminoti xizmatlari", "Газоснабжение", "供气事业", "Services de gaz") },
      { id: "environmental_utilities", name: row("Environmental Utilities", "Ekologik kommunal xizmatlar", "Экологические коммунальные услуги", "环境公用事业", "Services publics environnementaux") },
      { id: "utility_technology_and_services", name: row("Utility Technology & Services", "Kommunal texnologiyalar va xizmatlar", "Технологии и услуги коммунального хозяйства", "公用事业技术与服务", "Technologies et services publics") },
    ],
  },
  {
    id: "manufacturing_and_industrial",
    name: row("Manufacturing & Industrial", "Ishlab chiqarish va sanoat", "Обрабатывающая и тяжёлая промышленность", "制造业与工业", "Industrie manufacturière"),
    subsectors: [
      { id: "industrial_manufacturing", name: row("Industrial Manufacturing", "Sanoat ishlab chiqarishi", "Промышленное производство", "工业制造", "Fabrication industrielle") },
      { id: "machinery_and_equipment", name: row("Machinery & Equipment", "Mashinasozlik va uskunalar", "Машины и оборудование", "机械设备", "Machines et équipements") },
      { id: "electrical_equipment", name: row("Electrical Equipment", "Elektr uskunalari", "Электрооборудование", "电气设备", "Équipement électrique") },
      { id: "electronics_manufacturing", name: row("Electronics Manufacturing", "Elektronika ishlab chiqarish", "Производство электроники", "电子产品制造", "Fabrication électronique") },
      { id: "automotive_manufacturing", name: row("Automotive Manufacturing", "Avtomobilsozlik", "Автомобилестроение", "汽车制造", "Construction automobile") },
      { id: "aerospace_manufacturing", name: row("Aerospace Manufacturing", "Aerokosmik ishlab chiqarish", "Авиакосмическое производство", "航空航天制造", "Fabrication aérospatiale") },
      { id: "shipbuilding_and_marine_manufacturing", name: row("Shipbuilding & Marine Manufacturing", "Kemasozlik va dengiz sanoati", "Судостроение и морское производство", "造船与海洋制造", "Construction navale et fabrication maritime") },
      { id: "chemical_manufacturing", name: row("Chemical Manufacturing", "Kimyo sanoati", "Химическое производство", "化学品制造", "Fabrication chimique") },
      { id: "plastics_and_rubber", name: row("Plastics & Rubber", "Plastmassa va rezina", "Пластмассы и резина", "塑料与橡胶", "Plastique et caoutchouc") },
      { id: "glass_and_ceramics", name: row("Glass & Ceramics", "Shisha va keramika", "Стекло и керамика", "玻璃与陶瓷", "Verre et céramique") },
      { id: "cement_and_construction_materials", name: row("Cement & Construction Materials", "Sement va qurilish materiallari", "Цемент и строительные материалы", "水泥与建筑材料", "Ciment et matériaux de construction") },
      { id: "metals_and_steel", name: row("Metals & Steel", "Metallar va poʻlat", "Металлы и сталь", "金属与钢铁", "Métaux et acier") },
      { id: "textiles_and_apparel_manufacturing", name: row("Textiles & Apparel Manufacturing", "Toʻqimachilik va tikuvchilik ishlab chiqarishi", "Производство текстиля и одежды", "纺织与服装制造", "Fabrication de textiles et de vêtements") },
      { id: "leather_and_footwear_manufacturing", name: row("Leather & Footwear Manufacturing", "Charm va poyabzal ishlab chiqarish", "Производство кожи и обуви", "皮革与制鞋", "Fabrication de cuir et de chaussures") },
      { id: "paper_and_packaging", name: row("Paper & Packaging", "Qogʻoz va qadoqlash", "Бумага и упаковка", "造纸与包装", "Papier et emballage") },
      { id: "furniture_manufacturing", name: row("Furniture Manufacturing", "Mebel ishlab chiqarish", "Производство мебели", "家具制造", "Fabrication de meubles") },
      { id: "consumer_goods_manufacturing", name: row("Consumer Goods Manufacturing", "Isteʼmol tovarlari ishlab chiqarish", "Производство потребительских товаров", "消费品制造", "Fabrication de biens de consommation") },
      { id: "industrial_technology_and_automation", name: row("Industrial Technology & Automation", "Sanoat texnologiyalari va avtomatlashtirish", "Промышленные технологии и автоматизация", "工业技术与自动化", "Technologie industrielle et automatisation") },
    ],
  },
  {
    id: "construction_and_infrastructure",
    name: row("Construction & Infrastructure", "Qurilish va infratuzilma", "Строительство и инфраструктура", "建筑与基础设施", "Construction et infrastructures"),
    subsectors: [
      { id: "residential_construction", name: row("Residential Construction", "Turar-joy qurilishi", "Жилищное строительство", "住宅建筑", "Construction résidentielle") },
      { id: "commercial_construction", name: row("Commercial Construction", "Tijorat qurilishi", "Коммерческое строительство", "商业建筑", "Construction commerciale") },
      { id: "industrial_construction", name: row("Industrial Construction", "Sanoat qurilishi", "Промышленное строительство", "工业建筑", "Construction industrielle") },
      { id: "civil_engineering_and_infrastructure", name: row("Civil Engineering & Infrastructure", "Fuqarolik muhandisligi va infratuzilma", "Гражданское строительство и инфраструктура", "土木工程与基础设施", "Génie civil et infrastructures") },
      { id: "transportation_infrastructure", name: row("Transportation Infrastructure", "Transport infratuzilmasi", "Транспортная инфраструктура", "交通基础设施", "Infrastructures de transport") },
      { id: "energy_infrastructure", name: row("Energy Infrastructure", "Energetika infratuzilmasi", "Энергетическая инфраструктура", "能源基础设施", "Infrastructures énergétiques") },
      { id: "telecommunications_infrastructure", name: row("Telecommunications Infrastructure", "Telekommunikatsiya infratuzilmasi", "Телекоммуникационная инфраструктура", "电信基础设施", "Infrastructures de télécommunications") },
      { id: "water_infrastructure", name: row("Water Infrastructure", "Suv infratuzilmasi", "Водная инфраструктура", "水利基础设施", "Infrastructures hydrauliques") },
      { id: "construction_materials", name: row("Construction Materials", "Qurilish materiallari", "Строительные материалы", "建筑材料", "Matériaux de construction") },
      { id: "construction_equipment", name: row("Construction Equipment", "Qurilish texnikasi", "Строительная техника", "建筑设备", "Équipement de construction") },
      { id: "architecture_and_design", name: row("Architecture & Design", "Arxitektura va dizayn", "Архитектура и дизайн", "建筑与设计", "Architecture et design") },
      { id: "engineering_services", name: row("Engineering Services", "Muhandislik xizmatlari", "Инженерные услуги", "工程服务", "Services d'ingénierie") },
      { id: "construction_technology", name: row("Construction Technology", "Qurilish texnologiyalari", "Строительные технологии", "建筑科技", "Technologie de la construction") },
    ],
  },
  {
    id: "real_estate_and_property",
    name: row("Real Estate & Property", "Koʻchmas mulk", "Недвижимость", "房地产", "Immobilier"),
    subsectors: [
      { id: "residential_real_estate", name: row("Residential Real Estate", "Turar-joy koʻchmas mulki", "Жилая недвижимость", "住宅房地产", "Immobilier résidentiel") },
      { id: "commercial_real_estate", name: row("Commercial Real Estate", "Tijorat koʻchmas mulki", "Коммерческая недвижимость", "商业房地产", "Immobilier commercial") },
      { id: "industrial_real_estate", name: row("Industrial Real Estate", "Sanoat koʻchmas mulki", "Промышленная недвижимость", "工业房地产", "Immobilier industriel") },
      { id: "retail_real_estate", name: row("Retail Real Estate", "Chakana savdo koʻchmas mulki", "Торговая недвижимость", "零售房地产", "Immobilier commercial de détail") },
      { id: "hospitality_real_estate", name: row("Hospitality Real Estate", "Mehmonxona koʻchmas mulki", "Гостиничная недвижимость", "酒店房地产", "Immobilier hôtelier") },
      { id: "land_and_agricultural_real_estate", name: row("Land & Agricultural Real Estate", "Yer va qishloq xoʻjaligi koʻchmas mulki", "Земельная и сельскохозяйственная недвижимость", "土地与农业地产", "Immobilier foncier et agricole") },
      { id: "property_development", name: row("Property Development", "Koʻchmas mulkni rivojlantirish", "Девелопмент недвижимости", "地产开发", "Promotion immobilière") },
      { id: "property_management", name: row("Property Management", "Mulkni boshqarish", "Управление недвижимостью", "物业管理", "Gestion immobilière") },
      { id: "real_estate_brokerage", name: row("Real Estate Brokerage", "Koʻchmas mulk vositachiligi", "Риэлторские услуги", "房地产经纪", "Courtage immobilier") },
      { id: "real_estate_investment", name: row("Real Estate Investment", "Koʻchmas mulkka investitsiya", "Инвестиции в недвижимость", "房地产投资", "Investissement immobilier") },
      { id: "mortgage_and_property_finance", name: row("Mortgage & Property Finance", "Ipoteka va mulk moliyalashtirish", "Ипотека и финансирование недвижимости", "按揭与地产融资", "Financement hypothécaire et immobilier") },
      { id: "real_estate_technology", name: row("Real Estate Technology", "Koʻchmas mulk texnologiyalari", "Технологии в недвижимости", "房地产科技", "Technologie immobilière") },
    ],
  },
  {
    id: "transportation_and_mobility",
    name: row("Transportation & Mobility", "Transport va harakatchanlik", "Транспорт и мобильность", "交通与出行", "Transport et mobilité"),
    subsectors: [
      { id: "road_transportation", name: row("Road Transportation", "Avtomobil transporti", "Автомобильный транспорт", "公路运输", "Transport routier") },
      { id: "rail_transportation", name: row("Rail Transportation", "Temir yoʻl transporti", "Железнодорожный транспорт", "铁路运输", "Transport ferroviaire") },
      { id: "maritime_transportation", name: row("Maritime Transportation", "Dengiz transporti", "Морской транспорт", "海运", "Transport maritime") },
      { id: "aviation", name: row("Aviation", "Aviatsiya", "Авиация", "航空", "Aviation") },
      { id: "automotive", name: row("Automotive", "Avtomobilsozlik", "Автомобильная отрасль", "汽车业", "Automobile") },
      { id: "electric_vehicles", name: row("Electric Vehicles", "Elektromobillar", "Электромобили", "电动汽车", "Véhicules électriques") },
      { id: "autonomous_vehicles", name: row("Autonomous Vehicles", "Avtonom transport vositalari", "Беспилотные транспортные средства", "自动驾驶汽车", "Véhicules autonomes") },
      { id: "micromobility", name: row("Micromobility", "Mikroharakatchanlik", "Микромобильность", "微出行", "Micromobilité") },
      { id: "public_transportation", name: row("Public Transportation", "Jamoat transporti", "Общественный транспорт", "公共交通", "Transport public") },
      { id: "mobility_services", name: row("Mobility Services", "Harakatchanlik xizmatlari", "Услуги мобильности", "出行服务", "Services de mobilité") },
      { id: "fleet_services", name: row("Fleet Services", "Avtopark xizmatlari", "Услуги автопарка", "车队服务", "Services de gestion de flotte") },
      { id: "transportation_technology", name: row("Transportation Technology", "Transport texnologiyalari", "Транспортные технологии", "交通科技", "Technologie des transports") },
    ],
  },
  {
    id: "logistics_and_supply_chain",
    name: row("Logistics & Supply Chain", "Logistika va taʼminot zanjiri", "Логистика и цепочка поставок", "物流与供应链", "Logistique et chaîne d'approvisionnement"),
    subsectors: [
      { id: "freight_and_cargo", name: row("Freight & Cargo", "Yuk tashish", "Грузоперевозки", "货运", "Fret et cargaison") },
      { id: "freight_forwarding", name: row("Freight Forwarding", "Ekspeditorlik xizmatlari", "Транспортно-экспедиторские услуги", "货运代理", "Transit et affrètement") },
      { id: "warehousing", name: row("Warehousing", "Omborxona xizmatlari", "Складское хозяйство", "仓储", "Entreposage") },
      { id: "distribution_and_fulfillment", name: row("Distribution & Fulfillment", "Tarqatish va buyurtmalarni bajarish", "Дистрибуция и фулфилмент", "分销与订单履行", "Distribution et exécution des commandes") },
      { id: "courier_and_parcel_services", name: row("Courier & Parcel Services", "Kuryerlik va pochta xizmatlari", "Курьерские и почтовые услуги", "快递与包裹服务", "Services de courrier et de colis") },
      { id: "last_mile_delivery", name: row("Last-Mile Delivery", "Oxirgi bosqich yetkazib berish", "Доставка последней мили", "最后一公里配送", "Livraison du dernier kilomètre") },
      { id: "cold_chain_logistics", name: row("Cold Chain Logistics", "Sovuq zanjir logistikasi", "Холодовая логистика", "冷链物流", "Logistique de la chaîne du froid") },
      { id: "supply_chain_management", name: row("Supply Chain Management", "Taʼminot zanjirini boshqarish", "Управление цепочкой поставок", "供应链管理", "Gestion de la chaîne d'approvisionnement") },
      { id: "procurement_and_sourcing", name: row("Procurement & Sourcing", "Xarid va taʼminot manbalarini topish", "Закупки и снабжение", "采购与寻源", "Achats et approvisionnement") },
      { id: "logistics_technology", name: row("Logistics Technology", "Logistika texnologiyalari", "Логистические технологии", "物流科技", "Technologie logistique") },
    ],
  },
  {
    id: "wholesale_and_distribution",
    name: row("Wholesale & Distribution", "Ulgurji savdo va tarqatish", "Оптовая торговля и дистрибуция", "批发与分销", "Commerce de gros et distribution"),
    subsectors: [
      { id: "agricultural_wholesale", name: row("Agricultural Wholesale", "Qishloq xoʻjaligi ulgurji savdosi", "Оптовая торговля сельхозпродукцией", "农产品批发", "Commerce de gros agricole") },
      { id: "food_and_beverage_wholesale", name: row("Food & Beverage Wholesale", "Oziq-ovqat va ichimliklar ulgurji savdosi", "Оптовая торговля продуктами и напитками", "食品饮料批发", "Commerce de gros alimentaire et boissons") },
      { id: "industrial_wholesale", name: row("Industrial Wholesale", "Sanoat mahsulotlari ulgurji savdosi", "Оптовая торговля промышленными товарами", "工业品批发", "Commerce de gros industriel") },
      { id: "consumer_goods_wholesale", name: row("Consumer Goods Wholesale", "Isteʼmol tovarlari ulgurji savdosi", "Оптовая торговля потребительскими товарами", "消费品批发", "Commerce de gros de biens de consommation") },
      { id: "electronics_wholesale", name: row("Electronics Wholesale", "Elektronika ulgurji savdosi", "Оптовая торговля электроникой", "电子产品批发", "Commerce de gros d'électronique") },
      { id: "pharmaceutical_wholesale", name: row("Pharmaceutical Wholesale", "Farmatsevtika ulgurji savdosi", "Оптовая торговля фармацевтикой", "医药批发", "Commerce de gros pharmaceutique") },
      { id: "automotive_wholesale", name: row("Automotive Wholesale", "Avtomobil ulgurji savdosi", "Оптовая торговля автотоварами", "汽车批发", "Commerce de gros automobile") },
      { id: "construction_materials_wholesale", name: row("Construction Materials Wholesale", "Qurilish materiallari ulgurji savdosi", "Оптовая торговля стройматериалами", "建材批发", "Commerce de gros de matériaux de construction") },
      { id: "machinery_and_equipment_distribution", name: row("Machinery & Equipment Distribution", "Mashina va uskunalarni tarqatish", "Дистрибуция машин и оборудования", "机械设备分销", "Distribution de machines et équipements") },
      { id: "import_and_export", name: row("Import & Export", "Import va eksport", "Импорт и экспорт", "进出口", "Import et export") },
      { id: "b2b_distribution_platforms", name: row("B2B Distribution Platforms", "B2B tarqatish platformalari", "B2B-платформы дистрибуции", "B2B分销平台", "Plateformes de distribution B2B") },
    ],
  },
  {
    id: "retail_and_commerce",
    name: row("Retail & Commerce", "Chakana savdo va tijorat", "Розничная торговля", "零售与商业", "Commerce de détail"),
    subsectors: [
      { id: "grocery_and_food_retail", name: row("Grocery & Food Retail", "Oziq-ovqat chakana savdosi", "Продуктовая розница", "食品杂货零售", "Épicerie et alimentation") },
      { id: "general_merchandise_retail", name: row("General Merchandise Retail", "Umumiy tovarlar chakana savdosi", "Розница универсальных товаров", "综合商品零售", "Commerce de détail général") },
      { id: "apparel_and_fashion_retail", name: row("Apparel & Fashion Retail", "Kiyim va moda chakana savdosi", "Розница одежды и моды", "服装时尚零售", "Commerce de détail de mode et vêtements") },
      { id: "beauty_and_cosmetics_retail", name: row("Beauty & Cosmetics Retail", "Goʻzallik va kosmetika chakana savdosi", "Розница красоты и косметики", "美妆零售", "Commerce de détail beauté et cosmétiques") },
      { id: "electronics_retail", name: row("Electronics Retail", "Elektronika chakana savdosi", "Розница электроники", "电子产品零售", "Commerce de détail d'électronique") },
      { id: "furniture_and_home_retail", name: row("Furniture & Home Retail", "Mebel va uy-roʻzgʻor buyumlari chakana savdosi", "Розница мебели и товаров для дома", "家具家居零售", "Commerce de détail de meubles et maison") },
      { id: "automotive_retail", name: row("Automotive Retail", "Avtomobil chakana savdosi", "Розница автотоваров", "汽车零售", "Commerce de détail automobile") },
      { id: "pharmacy_and_health_retail", name: row("Pharmacy & Health Retail", "Dorixona va sogʻliqni saqlash chakana savdosi", "Розница аптечных и медицинских товаров", "药店与健康零售", "Commerce de détail pharmacie et santé") },
      { id: "specialty_retail", name: row("Specialty Retail", "Ixtisoslashgan chakana savdo", "Специализированная розница", "专业零售", "Commerce de détail spécialisé") },
      { id: "luxury_retail", name: row("Luxury Retail", "Hashamatli tovarlar chakana savdosi", "Розница люксовых товаров", "奢侈品零售", "Commerce de détail de luxe") },
      { id: "e_commerce", name: row("E-commerce", "Elektron tijorat", "Электронная коммерция", "电子商务", "Commerce électronique") },
      { id: "marketplaces", name: row("Marketplaces", "Onlayn savdo maydonchalari", "Маркетплейсы", "电商平台", "Places de marché") },
      { id: "retail_technology", name: row("Retail Technology", "Chakana savdo texnologiyalari", "Розничные технологии", "零售科技", "Technologie du commerce de détail") },
    ],
  },
  {
    id: "financial_services_and_fintech",
    name: row("Financial Services & Fintech", "Moliyaviy xizmatlar va fintex", "Финансовые услуги и финтех", "金融服务与金融科技", "Services financiers et fintech"),
    subsectors: [
      { id: "banking", name: row("Banking", "Bank ishi", "Банковское дело", "银行业", "Banque") },
      { id: "lending_and_credit", name: row("Lending & Credit", "Kreditlash", "Кредитование", "借贷与信贷", "Prêt et crédit") },
      { id: "payments", name: row("Payments", "Toʻlovlar", "Платежи", "支付", "Paiements") },
      { id: "money_transfer_and_remittances", name: row("Money Transfer & Remittances", "Pul oʻtkazmalari", "Денежные переводы", "汇款", "Transferts d'argent et envois de fonds") },
      { id: "investment_and_brokerage", name: row("Investment & Brokerage", "Investitsiya va bróker xizmatlari", "Инвестиции и брокерские услуги", "投资与经纪", "Investissement et courtage") },
      { id: "asset_management", name: row("Asset Management", "Aktivlarni boshqarish", "Управление активами", "资产管理", "Gestion d'actifs") },
      { id: "wealth_management", name: row("Wealth Management", "Boylikni boshqarish", "Управление капиталом", "财富管理", "Gestion de patrimoine") },
      { id: "capital_markets", name: row("Capital Markets", "Kapital bozorlari", "Рынки капитала", "资本市场", "Marchés des capitaux") },
      { id: "consumer_finance", name: row("Consumer Finance", "Isteʼmolchi moliyasi", "Потребительское финансирование", "消费金融", "Finance à la consommation") },
      { id: "corporate_finance", name: row("Corporate Finance", "Korporativ moliya", "Корпоративные финансы", "公司金融", "Finance d'entreprise") },
      { id: "financial_infrastructure", name: row("Financial Infrastructure", "Moliyaviy infratuzilma", "Финансовая инфраструктура", "金融基础设施", "Infrastructure financière") },
      { id: "fintech", name: row("Fintech", "Fintex", "Финтех", "金融科技", "Fintech") },
      { id: "digital_banking", name: row("Digital Banking", "Raqamli bank xizmatlari", "Цифровой банкинг", "数字银行", "Banque numérique") },
      { id: "cryptocurrency_and_digital_assets", name: row("Cryptocurrency & Digital Assets", "Kriptovalyuta va raqamli aktivlar", "Криптовалюта и цифровые активы", "加密货币与数字资产", "Cryptomonnaies et actifs numériques") },
      { id: "blockchain_and_decentralized_finance", name: row("Blockchain & Decentralized Finance", "Bloklar zanjiri va markazlashmagan moliya", "Блокчейн и децентрализованные финансы", "区块链与去中心化金融", "Blockchain et finance décentralisée") },
    ],
  },
  {
    id: "insurance_and_risk_management",
    name: row("Insurance & Risk Management", "Sugʻurta va xavflarni boshqarish", "Страхование и управление рисками", "保险与风险管理", "Assurance et gestion des risques"),
    subsectors: [
      { id: "life_insurance", name: row("Life Insurance", "Hayotni sugʻurtalash", "Страхование жизни", "人寿保险", "Assurance-vie") },
      { id: "health_insurance", name: row("Health Insurance", "Tibbiy sugʻurta", "Медицинское страхование", "健康保险", "Assurance maladie") },
      { id: "property_and_casualty_insurance", name: row("Property & Casualty Insurance", "Mulk va falokat sugʻurtasi", "Имущественное страхование", "财产与意外保险", "Assurance de biens et de dommages") },
      { id: "automotive_insurance", name: row("Automotive Insurance", "Avto-sugʻurta", "Автострахование", "车险", "Assurance automobile") },
      { id: "commercial_insurance", name: row("Commercial Insurance", "Tijorat sugʻurtasi", "Коммерческое страхование", "商业保险", "Assurance commerciale") },
      { id: "agricultural_insurance", name: row("Agricultural Insurance", "Qishloq xoʻjaligi sugʻurtasi", "Сельскохозяйственное страхование", "农业保险", "Assurance agricole") },
      { id: "specialty_insurance", name: row("Specialty Insurance", "Ixtisoslashgan sugʻurta", "Специализированное страхование", "专业保险", "Assurance spécialisée") },
      { id: "reinsurance", name: row("Reinsurance", "Qayta sugʻurtalash", "Перестрахование", "再保险", "Réassurance") },
      { id: "insurance_brokerage", name: row("Insurance Brokerage", "Sugʻurta vositachiligi", "Страховое брокерство", "保险经纪", "Courtage d'assurance") },
      { id: "risk_management", name: row("Risk Management", "Xavflarni boshqarish", "Управление рисками", "风险管理", "Gestion des risques") },
      { id: "insurtech", name: row("Insurtech", "Insurtex", "Инсуртех", "保险科技", "Assurtech") },
    ],
  },
  {
    id: "information_technology_and_software",
    name: row("Information Technology & Software", "Axborot texnologiyalari va dasturiy taʼminot", "Информационные технологии и программное обеспечение", "信息技术与软件", "Technologies de l'information et logiciels"),
    subsectors: [
      { id: "enterprise_software", name: row("Enterprise Software", "Korporativ dasturiy taʼminot", "Корпоративное ПО", "企业软件", "Logiciels d'entreprise") },
      { id: "business_software", name: row("Business Software", "Biznes dasturiy taʼminoti", "Бизнес-ПО", "商业软件", "Logiciels professionnels") },
      { id: "saas", name: row("SaaS", "SaaS (xizmat sifatida dastur)", "SaaS (ПО как услуга)", "SaaS(软件即服务)", "SaaS (logiciel en tant que service)") },
      { id: "cloud_computing", name: row("Cloud Computing", "Bulutli hisoblash", "Облачные вычисления", "云计算", "Informatique en nuage") },
      { id: "it_infrastructure", name: row("IT Infrastructure", "AT infratuzilmasi", "ИТ-инфраструктура", "IT基础设施", "Infrastructure informatique") },
      { id: "software_development", name: row("Software Development", "Dasturiy taʼminot ishlab chiqish", "Разработка ПО", "软件开发", "Développement logiciel") },
      { id: "developer_technology", name: row("Developer Technology", "Dasturchilar uchun texnologiyalar", "Технологии для разработчиков", "开发者技术", "Technologie pour développeurs") },
      { id: "it_services", name: row("IT Services", "AT xizmatlari", "ИТ-услуги", "IT服务", "Services informatiques") },
      { id: "systems_integration", name: row("Systems Integration", "Tizimlarni integratsiyalash", "Системная интеграция", "系统集成", "Intégration de systèmes") },
      { id: "managed_it_services", name: row("Managed IT Services", "Boshqariladigan AT xizmatlari", "Управляемые ИТ-услуги", "托管IT服务", "Services informatiques gérés") },
      { id: "digital_transformation", name: row("Digital Transformation", "Raqamli transformatsiya", "Цифровая трансформация", "数字化转型", "Transformation numérique") },
      { id: "low_code_and_no_code_technology", name: row("Low-Code & No-Code Technology", "Kam kodli va kodsiz texnologiyalar", "Low-code и no-code технологии", "低代码与无代码技术", "Technologies low-code et no-code") },
    ],
  },
  {
    id: "artificial_intelligence_and_machine_learning",
    name: row("Artificial Intelligence & Machine Learning", "Sunʼiy intellekt va mashinaviy oʻqitish", "Искусственный интеллект и машинное обучение", "人工智能与机器学习", "Intelligence artificielle et apprentissage automatique"),
    subsectors: [
      { id: "generative_ai", name: row("Generative AI", "Generativ sunʼiy intellekt", "Генеративный ИИ", "生成式人工智能", "IA générative") },
      { id: "ai_applications", name: row("AI Applications", "Sunʼiy intellekt ilovalari", "Приложения ИИ", "人工智能应用", "Applications de l'IA") },
      { id: "ai_infrastructure", name: row("AI Infrastructure", "Sunʼiy intellekt infratuzilmasi", "Инфраструктура ИИ", "人工智能基础设施", "Infrastructure d'IA") },
      { id: "machine_learning", name: row("Machine Learning", "Mashinaviy oʻqitish", "Машинное обучение", "机器学习", "Apprentissage automatique") },
      { id: "computer_vision", name: row("Computer Vision", "Kompyuter koʻrishi", "Компьютерное зрение", "计算机视觉", "Vision par ordinateur") },
      { id: "natural_language_ai", name: row("Natural Language AI", "Tabiiy tilni qayta ishlovchi sunʼiy intellekt", "ИИ обработки естественного языка", "自然语言人工智能", "IA du langage naturel") },
      { id: "speech_and_voice_ai", name: row("Speech & Voice AI", "Nutq va ovoz sunʼiy intellekti", "Речевой и голосовой ИИ", "语音人工智能", "IA vocale") },
      { id: "ai_agents_and_automation", name: row("AI Agents & Automation", "Sunʼiy intellekt agentlari va avtomatlashtirish", "ИИ-агенты и автоматизация", "人工智能代理与自动化", "Agents IA et automatisation") },
      { id: "enterprise_ai", name: row("Enterprise AI", "Korporativ sunʼiy intellekt", "Корпоративный ИИ", "企业人工智能", "IA d'entreprise") },
      { id: "ai_robotics", name: row("AI Robotics", "Sunʼiy intellektli robototexnika", "ИИ-робототехника", "人工智能机器人", "Robotique IA") },
      { id: "ai_services", name: row("AI Services", "Sunʼiy intellekt xizmatlari", "Услуги в области ИИ", "人工智能服务", "Services d'IA") },
      { id: "ai_safety_and_governance", name: row("AI Safety & Governance", "Sunʼiy intellekt xavfsizligi va boshqaruvi", "Безопасность и регулирование ИИ", "人工智能安全与治理", "Sécurité et gouvernance de l'IA") },
    ],
  },
  {
    id: "data_and_analytics",
    name: row("Data & Analytics", "Maʼlumotlar va tahlil", "Данные и аналитика", "数据与分析", "Données et analytique"),
    subsectors: [
      { id: "data_infrastructure", name: row("Data Infrastructure", "Maʼlumotlar infratuzilmasi", "Инфраструктура данных", "数据基础设施", "Infrastructure de données") },
      { id: "data_management", name: row("Data Management", "Maʼlumotlarni boshqarish", "Управление данными", "数据管理", "Gestion des données") },
      { id: "data_engineering", name: row("Data Engineering", "Maʼlumotlar muhandisligi", "Инженерия данных", "数据工程", "Ingénierie des données") },
      { id: "data_analytics", name: row("Data Analytics", "Maʼlumotlar tahlili", "Аналитика данных", "数据分析", "Analytique des données") },
      { id: "business_intelligence", name: row("Business Intelligence", "Biznes-tahlil", "Бизнес-аналитика", "商业智能", "Intelligence économique") },
      { id: "big_data", name: row("Big Data", "Katta maʼlumotlar", "Большие данные", "大数据", "Big Data") },
      { id: "data_platforms", name: row("Data Platforms", "Maʼlumotlar platformalari", "Платформы данных", "数据平台", "Plateformes de données") },
      { id: "data_marketplaces", name: row("Data Marketplaces", "Maʼlumotlar savdo maydonchalari", "Маркетплейсы данных", "数据交易平台", "Places de marché de données") },
      { id: "data_governance", name: row("Data Governance", "Maʼlumotlarni boshqaruvi (governance)", "Управление данными (governance)", "数据治理", "Gouvernance des données") },
      { id: "data_privacy", name: row("Data Privacy", "Maʼlumotlar maxfiyligi", "Конфиденциальность данных", "数据隐私", "Confidentialité des données") },
      { id: "geospatial_technology", name: row("Geospatial Technology", "Geofazoviy texnologiyalar", "Геопространственные технологии", "地理空间技术", "Technologie géospatiale") },
      { id: "data_services", name: row("Data Services", "Maʼlumotlar xizmatlari", "Услуги по работе с данными", "数据服务", "Services de données") },
    ],
  },
  {
    id: "cybersecurity_and_digital_trust",
    name: row("Cybersecurity & Digital Trust", "Kiberxavfsizlik va raqamli ishonch", "Кибербезопасность и цифровое доверие", "网络安全与数字信任", "Cybersécurité et confiance numérique"),
    subsectors: [
      { id: "cybersecurity", name: row("Cybersecurity", "Kiberxavfsizlik", "Кибербезопасность", "网络安全", "Cybersécurité") },
      { id: "network_security", name: row("Network Security", "Tarmoq xavfsizligi", "Сетевая безопасность", "网络安全（网络层）", "Sécurité des réseaux") },
      { id: "cloud_security", name: row("Cloud Security", "Bulutli xavfsizlik", "Облачная безопасность", "云安全", "Sécurité du cloud") },
      { id: "application_security", name: row("Application Security", "Ilovalar xavfsizligi", "Безопасность приложений", "应用安全", "Sécurité des applications") },
      { id: "identity_and_access_management", name: row("Identity & Access Management", "Shaxsni va kirishni boshqarish", "Управление идентификацией и доступом", "身份与访问管理", "Gestion des identités et des accès") },
      { id: "data_security", name: row("Data Security", "Maʼlumotlar xavfsizligi", "Безопасность данных", "数据安全", "Sécurité des données") },
      { id: "threat_intelligence", name: row("Threat Intelligence", "Tahdidlar razvedkasi", "Аналитика угроз", "威胁情报", "Renseignement sur les menaces") },
      { id: "security_operations", name: row("Security Operations", "Xavfsizlik operatsiyalari", "Операции по обеспечению безопасности", "安全运营", "Opérations de sécurité") },
      { id: "fraud_prevention", name: row("Fraud Prevention", "Firibgarlikning oldini olish", "Предотвращение мошенничества", "反欺诈", "Prévention de la fraude") },
      { id: "privacy_technology", name: row("Privacy Technology", "Maxfiylik texnologiyalari", "Технологии конфиденциальности", "隐私技术", "Technologie de la confidentialité") },
      { id: "digital_identity", name: row("Digital Identity", "Raqamli shaxsni tasdiqlash", "Цифровая идентификация", "数字身份", "Identité numérique") },
      { id: "cybersecurity_services", name: row("Cybersecurity Services", "Kiberxavfsizlik xizmatlari", "Услуги кибербезопасности", "网络安全服务", "Services de cybersécurité") },
    ],
  },
  {
    id: "telecommunications_and_connectivity",
    name: row("Telecommunications & Connectivity", "Telekommunikatsiya va aloqa", "Телекоммуникации и связь", "电信与连接", "Télécommunications et connectivité"),
    subsectors: [
      { id: "telecommunications", name: row("Telecommunications", "Telekommunikatsiya", "Телекоммуникации", "电信", "Télécommunications") },
      { id: "mobile_networks", name: row("Mobile Networks", "Mobil tarmoqlar", "Мобильные сети", "移动网络", "Réseaux mobiles") },
      { id: "broadband_and_internet", name: row("Broadband & Internet", "Keng polosali va internet aloqasi", "Широкополосный доступ и интернет", "宽带与互联网", "Haut débit et internet") },
      { id: "fiber_networks", name: row("Fiber Networks", "Optik-tolali tarmoqlar", "Оптоволоконные сети", "光纤网络", "Réseaux de fibre optique") },
      { id: "satellite_communications", name: row("Satellite Communications", "Sputnik aloqasi", "Спутниковая связь", "卫星通信", "Communications par satellite") },
      { id: "network_infrastructure", name: row("Network Infrastructure", "Tarmoq infratuzilmasi", "Сетевая инфраструктура", "网络基础设施", "Infrastructure réseau") },
      { id: "telecom_equipment", name: row("Telecom Equipment", "Telekommunikatsiya uskunalari", "Телекоммуникационное оборудование", "电信设备", "Équipement de télécommunications") },
      { id: "telecom_software", name: row("Telecom Software", "Telekommunikatsiya dasturiy taʼminoti", "Телекоммуникационное ПО", "电信软件", "Logiciels de télécommunications") },
      { id: "internet_services", name: row("Internet Services", "Internet xizmatlari", "Интернет-услуги", "互联网服务", "Services internet") },
      { id: "iot_connectivity", name: row("IoT Connectivity", "Narsalar interneti (IoT) ulanishi", "IoT-связь", "物联网连接", "Connectivité IoT") },
      { id: "edge_computing", name: row("Edge Computing", "Chekka hisoblash (edge computing)", "Периферийные вычисления", "边缘计算", "Informatique en périphérie") },
      { id: "next_generation_connectivity", name: row("Next-Generation Connectivity", "Yangi avlod aloqasi", "Связь нового поколения", "下一代连接技术", "Connectivité de nouvelle génération") },
    ],
  },
  {
    id: "semiconductors_electronics_and_computing",
    name: row("Semiconductors, Electronics & Computing", "Yarimoʻtkazgichlar, elektronika va hisoblash texnikasi", "Полупроводники, электроника и вычислительная техника", "半导体、电子与计算", "Semi-conducteurs, électronique et informatique"),
    subsectors: [
      { id: "semiconductor_design", name: row("Semiconductor Design", "Yarimoʻtkazgichlarni loyihalash", "Проектирование полупроводников", "半导体设计", "Conception de semi-conducteurs") },
      { id: "semiconductor_manufacturing", name: row("Semiconductor Manufacturing", "Yarimoʻtkazgich ishlab chiqarish", "Производство полупроводников", "半导体制造", "Fabrication de semi-conducteurs") },
      { id: "semiconductor_equipment", name: row("Semiconductor Equipment", "Yarimoʻtkazgich uskunalari", "Оборудование для полупроводников", "半导体设备", "Équipement pour semi-conducteurs") },
      { id: "semiconductor_materials", name: row("Semiconductor Materials", "Yarimoʻtkazgich materiallari", "Материалы для полупроводников", "半导体材料", "Matériaux pour semi-conducteurs") },
      { id: "microprocessors_and_gpus", name: row("Microprocessors & GPUs", "Mikroprotsessorlar va GPU", "Микропроцессоры и GPU", "微处理器与GPU", "Microprocesseurs et GPU") },
      { id: "ai_chips", name: row("AI Chips", "Sunʼiy intellekt chiplari", "ИИ-чипы", "人工智能芯片", "Puces IA") },
      { id: "memory_technology", name: row("Memory Technology", "Xotira texnologiyalari", "Технологии памяти", "存储技术", "Technologie de mémoire") },
      { id: "sensors_and_components", name: row("Sensors & Components", "Sensorlar va komponentlar", "Датчики и компоненты", "传感器与元器件", "Capteurs et composants") },
      { id: "photonics", name: row("Photonics", "Fotonika", "Фотоника", "光子学", "Photonique") },
      { id: "advanced_computing", name: row("Advanced Computing", "Ilgʻor hisoblash texnologiyalari", "Передовые вычисления", "先进计算", "Informatique avancée") },
      { id: "electronics_technology", name: row("Electronics Technology", "Elektronika texnologiyalari", "Электронные технологии", "电子技术", "Technologie électronique") },
    ],
  },
  {
    id: "robotics_and_automation",
    name: row("Robotics & Automation", "Robototexnika va avtomatlashtirish", "Робототехника и автоматизация", "机器人与自动化", "Robotique et automatisation"),
    subsectors: [
      { id: "industrial_robotics", name: row("Industrial Robotics", "Sanoat robototexnikasi", "Промышленная робототехника", "工业机器人", "Robotique industrielle") },
      { id: "service_robotics", name: row("Service Robotics", "Xizmat koʻrsatuvchi robototexnika", "Сервисная робототехника", "服务机器人", "Robotique de service") },
      { id: "warehouse_robotics", name: row("Warehouse Robotics", "Ombor robototexnikasi", "Складская робототехника", "仓储机器人", "Robotique d'entrepôt") },
      { id: "agricultural_robotics", name: row("Agricultural Robotics", "Qishloq xoʻjaligi robototexnikasi", "Сельскохозяйственная робототехника", "农业机器人", "Robotique agricole") },
      { id: "healthcare_robotics", name: row("Healthcare Robotics", "Tibbiyot robototexnikasi", "Медицинская робототехника", "医疗机器人", "Robotique médicale") },
      { id: "construction_robotics", name: row("Construction Robotics", "Qurilish robototexnikasi", "Строительная робототехника", "建筑机器人", "Robotique de construction") },
      { id: "consumer_robotics", name: row("Consumer Robotics", "Isteʼmolchi robototexnikasi", "Потребительская робототехника", "消费级机器人", "Robotique grand public") },
      { id: "autonomous_systems", name: row("Autonomous Systems", "Avtonom tizimlar", "Автономные системы", "自主系统", "Systèmes autonomes") },
      { id: "drones_and_unmanned_systems", name: row("Drones & Unmanned Systems", "Dronlar va boshqarilmaydigan tizimlar", "Дроны и беспилотные системы", "无人机与无人系统", "Drones et systèmes sans pilote") },
      { id: "robotic_process_automation", name: row("Robotic Process Automation", "Robotlashtirilgan jarayonlarni avtomatlashtirish", "Роботизированная автоматизация процессов", "机器人流程自动化", "Automatisation robotisée des processus") },
      { id: "robotics_software", name: row("Robotics Software", "Robototexnika dasturiy taʼminoti", "ПО для робототехники", "机器人软件", "Logiciels de robotique") },
    ],
  },
  {
    id: "healthcare_and_medical_services",
    name: row("Healthcare & Medical Services", "Sogʻliqni saqlash va tibbiy xizmatlar", "Здравоохранение и медицинские услуги", "医疗保健与医疗服务", "Santé et services médicaux"),
    subsectors: [
      { id: "hospitals", name: row("Hospitals", "Kasalxonalar", "Больницы", "医院", "Hôpitaux") },
      { id: "primary_healthcare", name: row("Primary Healthcare", "Birlamchi tibbiy yordam", "Первичная медицинская помощь", "初级医疗保健", "Soins de santé primaires") },
      { id: "specialist_healthcare", name: row("Specialist Healthcare", "Ixtisoslashgan tibbiy yordam", "Специализированная медицинская помощь", "专科医疗", "Soins de santé spécialisés") },
      { id: "dental_services", name: row("Dental Services", "Stomatologiya xizmatlari", "Стоматологические услуги", "牙科服务", "Services dentaires") },
      { id: "mental_healthcare", name: row("Mental Healthcare", "Ruhiy salomatlik xizmatlari", "Психиатрическая помощь", "心理健康服务", "Soins de santé mentale") },
      { id: "elder_care", name: row("Elder Care", "Qariyalar parvarishi", "Уход за пожилыми людьми", "老年护理", "Soins aux personnes âgées") },
      { id: "home_healthcare", name: row("Home Healthcare", "Uyda tibbiy parvarish", "Медицинская помощь на дому", "居家医疗护理", "Soins de santé à domicile") },
      { id: "rehabilitation", name: row("Rehabilitation", "Reabilitatsiya", "Реабилитация", "康复", "Réadaptation") },
      { id: "diagnostics", name: row("Diagnostics", "Diagnostika", "Диагностика", "诊断", "Diagnostic") },
      { id: "medical_laboratories", name: row("Medical Laboratories", "Tibbiyot laboratoriyalari", "Медицинские лаборатории", "医学实验室", "Laboratoires médicaux") },
      { id: "medical_imaging", name: row("Medical Imaging", "Tibbiy tasvirlash", "Медицинская визуализация", "医学影像", "Imagerie médicale") },
      { id: "pharmacies", name: row("Pharmacies", "Dorixonalar", "Аптеки", "药店", "Pharmacies") },
      { id: "healthcare_administration", name: row("Healthcare Administration", "Sogʻliqni saqlashni boshqarish", "Управление здравоохранением", "医疗管理", "Administration de la santé") },
      { id: "healthcare_technology", name: row("Healthcare Technology", "Sogʻliqni saqlash texnologiyalari", "Медицинские технологии", "医疗科技", "Technologie de la santé") },
    ],
  },
  {
    id: "pharmaceuticals_biotechnology_and_life_sciences",
    name: row("Pharmaceuticals, Biotechnology & Life Sciences", "Farmatsevtika, biotexnologiya va tabiiy fanlar", "Фармацевтика, биотехнологии и науки о жизни", "制药、生物技术与生命科学", "Pharmacie, biotechnologie et sciences de la vie"),
    subsectors: [
      { id: "pharmaceuticals", name: row("Pharmaceuticals", "Farmatsevtika", "Фармацевтика", "制药", "Pharmacie") },
      { id: "biotechnology", name: row("Biotechnology", "Biotexnologiya", "Биотехнологии", "生物技术", "Biotechnologie") },
      { id: "drug_discovery", name: row("Drug Discovery", "Dori vositalarini kashf etish", "Разработка лекарств", "药物研发", "Découverte de médicaments") },
      { id: "clinical_research", name: row("Clinical Research", "Klinik tadqiqotlar", "Клинические исследования", "临床研究", "Recherche clinique") },
      { id: "genomics", name: row("Genomics", "Genomika", "Геномика", "基因组学", "Génomique") },
      { id: "gene_therapy", name: row("Gene Therapy", "Gen terapiyasi", "Генная терапия", "基因治疗", "Thérapie génique") },
      { id: "cell_therapy", name: row("Cell Therapy", "Hujayra terapiyasi", "Клеточная терапия", "细胞治疗", "Thérapie cellulaire") },
      { id: "synthetic_biology", name: row("Synthetic Biology", "Sintetik biologiya", "Синтетическая биология", "合成生物学", "Biologie synthétique") },
      { id: "bioinformatics", name: row("Bioinformatics", "Bioinformatika", "Биоинформатика", "生物信息学", "Bio-informatique") },
      { id: "agricultural_biotechnology", name: row("Agricultural Biotechnology", "Qishloq xoʻjaligi biotexnologiyasi", "Сельскохозяйственные биотехнологии", "农业生物技术", "Biotechnologie agricole") },
      { id: "industrial_biotechnology", name: row("Industrial Biotechnology", "Sanoat biotexnologiyasi", "Промышленные биотехнологии", "工业生物技术", "Biotechnologie industrielle") },
      { id: "life_sciences_services", name: row("Life Sciences Services", "Tabiiy fanlar xizmatlari", "Услуги в области наук о жизни", "生命科学服务", "Services en sciences de la vie") },
    ],
  },
  {
    id: "medical_technology_and_digital_health",
    name: row("Medical Technology & Digital Health", "Tibbiy texnologiyalar va raqamli salomatlik", "Медицинские технологии и цифровое здравоохранение", "医疗技术与数字健康", "Technologie médicale et santé numérique"),
    subsectors: [
      { id: "medical_devices", name: row("Medical Devices", "Tibbiy asboblar", "Медицинские устройства", "医疗器械", "Dispositifs médicaux") },
      { id: "surgical_technology", name: row("Surgical Technology", "Jarrohlik texnologiyalari", "Хирургические технологии", "外科技术", "Technologie chirurgicale") },
      { id: "diagnostic_technology", name: row("Diagnostic Technology", "Diagnostika texnologiyalari", "Диагностические технологии", "诊断技术", "Technologie de diagnostic") },
      { id: "medical_imaging_technology", name: row("Medical Imaging Technology", "Tibbiy tasvirlash texnologiyalari", "Технологии медицинской визуализации", "医学影像技术", "Technologie d'imagerie médicale") },
      { id: "digital_health", name: row("Digital Health", "Raqamli salomatlik", "Цифровое здравоохранение", "数字健康", "Santé numérique") },
      { id: "telemedicine", name: row("Telemedicine", "Telemeditsina", "Телемедицина", "远程医疗", "Télémédecine") },
      { id: "digital_therapeutics", name: row("Digital Therapeutics", "Raqamli terapevtika", "Цифровая терапия", "数字疗法", "Thérapeutique numérique") },
      { id: "health_platforms", name: row("Health Platforms", "Salomatlik platformalari", "Платформы здравоохранения", "健康平台", "Plateformes de santé") },
      { id: "wearable_health_technology", name: row("Wearable Health Technology", "Kiyiladigan salomatlik texnologiyalari", "Носимые медицинские устройства", "可穿戴健康技术", "Technologie de santé portable") },
      { id: "healthcare_ai", name: row("Healthcare AI", "Sogʻliqni saqlashda sunʼiy intellekt", "ИИ в здравоохранении", "医疗人工智能", "IA de la santé") },
      { id: "medical_robotics", name: row("Medical Robotics", "Tibbiyot robototexnikasi", "Медицинская робототехника", "医疗机器人技术", "Robotique médicale") },
      { id: "health_data_technology", name: row("Health Data Technology", "Salomatlik maʼlumotlari texnologiyalari", "Технологии медицинских данных", "健康数据技术", "Technologie des données de santé") },
    ],
  },
  {
    id: "education_and_edtech",
    name: row("Education & EdTech", "Taʼlim va taʼlim texnologiyalari", "Образование и EdTech", "教育与教育科技", "Éducation et EdTech"),
    subsectors: [
      { id: "early_childhood_education", name: row("Early Childhood Education", "Maktabgacha taʼlim", "Дошкольное образование", "学前教育", "Éducation de la petite enfance") },
      { id: "primary_and_secondary_education", name: row("Primary & Secondary Education", "Umumiy oʻrta taʼlim", "Начальное и среднее образование", "中小学教育", "Éducation primaire et secondaire") },
      { id: "higher_education", name: row("Higher Education", "Oliy taʼlim", "Высшее образование", "高等教育", "Enseignement supérieur") },
      { id: "vocational_education", name: row("Vocational Education", "Kasb-hunar taʼlimi", "Профессиональное образование", "职业教育", "Enseignement professionnel") },
      { id: "professional_education", name: row("Professional Education", "Malaka oshirish taʼlimi", "Профессиональное повышение квалификации", "职业进修教育", "Formation professionnelle continue") },
      { id: "online_education", name: row("Online Education", "Onlayn taʼlim", "Онлайн-образование", "在线教育", "Éducation en ligne") },
      { id: "tutoring_and_test_preparation", name: row("Tutoring & Test Preparation", "Repetitorlik va imtihonlarga tayyorlash", "Репетиторство и подготовка к экзаменам", "辅导与考试培训", "Tutorat et préparation aux examens") },
      { id: "language_education", name: row("Language Education", "Til oʻrgatish", "Языковое обучение", "语言教育", "Enseignement des langues") },
      { id: "corporate_learning", name: row("Corporate Learning", "Korporativ oʻqitish", "Корпоративное обучение", "企业培训", "Formation en entreprise") },
      { id: "educational_content", name: row("Educational Content", "Taʼlim kontenti", "Образовательный контент", "教育内容", "Contenu éducatif") },
      { id: "learning_technology", name: row("Learning Technology", "Oʻqitish texnologiyalari", "Образовательные технологии", "学习技术", "Technologie de l'apprentissage") },
      { id: "education_platforms", name: row("Education Platforms", "Taʼlim platformalari", "Образовательные платформы", "教育平台", "Plateformes éducatives") },
    ],
  },
  {
    id: "professional_services",
    name: row("Professional Services", "Professional xizmatlar", "Профессиональные услуги", "专业服务", "Services professionnels"),
    subsectors: [
      { id: "legal_services", name: row("Legal Services", "Yuridik xizmatlar", "Юридические услуги", "法律服务", "Services juridiques") },
      { id: "accounting_and_auditing", name: row("Accounting & Auditing", "Buxgalteriya hisobi va audit", "Бухгалтерский учёт и аудит", "会计与审计", "Comptabilité et audit") },
      { id: "tax_services", name: row("Tax Services", "Soliq xizmatlari", "Налоговые услуги", "税务服务", "Services fiscaux") },
      { id: "management_consulting", name: row("Management Consulting", "Boshqaruv konsaltingi", "Управленческий консалтинг", "管理咨询", "Conseil en management") },
      { id: "strategy_consulting", name: row("Strategy Consulting", "Strategik konsalting", "Стратегический консалтинг", "战略咨询", "Conseil en stratégie") },
      { id: "it_consulting", name: row("IT Consulting", "AT konsalting", "ИТ-консалтинг", "IT咨询", "Conseil en informatique") },
      { id: "engineering_services", name: row("Engineering Services", "Muhandislik xizmatlari", "Инженерные услуги", "工程服务", "Services d'ingénierie") },
      { id: "architecture_services", name: row("Architecture Services", "Arxitektura xizmatlari", "Архитектурные услуги", "建筑设计服务", "Services d'architecture") },
      { id: "scientific_services", name: row("Scientific Services", "Ilmiy xizmatlar", "Научные услуги", "科学服务", "Services scientifiques") },
      { id: "market_research", name: row("Market Research", "Bozorni tadqiq qilish", "Маркетинговые исследования", "市场调研", "Études de marché") },
      { id: "design_services", name: row("Design Services", "Dizayn xizmatlari", "Дизайнерские услуги", "设计服务", "Services de design") },
      { id: "translation_and_localization", name: row("Translation & Localization", "Tarjima va lokalizatsiya", "Перевод и локализация", "翻译与本地化", "Traduction et localisation") },
      { id: "certification_and_testing", name: row("Certification & Testing", "Sertifikatlashtirish va sinovdan oʻtkazish", "Сертификация и испытания", "认证与检测", "Certification et essais") },
      { id: "intellectual_property_services", name: row("Intellectual Property Services", "Intellektual mulk xizmatlari", "Услуги в сфере интеллектуальной собственности", "知识产权服务", "Services de propriété intellectuelle") },
    ],
  },
  {
    id: "business_services",
    name: row("Business Services", "Biznes xizmatlari", "Бизнес-услуги", "商业服务", "Services aux entreprises"),
    subsectors: [
      { id: "business_process_outsourcing", name: row("Business Process Outsourcing", "Biznes-jarayonlarni autsorsing qilish", "Аутсорсинг бизнес-процессов", "业务流程外包", "Externalisation des processus métier") },
      { id: "customer_support_services", name: row("Customer Support Services", "Mijozlarni qoʻllab-quvvatlash xizmatlari", "Услуги поддержки клиентов", "客户支持服务", "Services de support client") },
      { id: "human_resources_services", name: row("Human Resources Services", "Inson resurslari xizmatlari", "Услуги в области управления персоналом", "人力资源服务", "Services de ressources humaines") },
      { id: "recruitment_and_staffing", name: row("Recruitment & Staffing", "Xodimlarni yollash va taʼminlash", "Подбор персонала и кадровые услуги", "招聘与人才派遣", "Recrutement et intérim") },
      { id: "payroll_services", name: row("Payroll Services", "Ish haqi hisob-kitobi xizmatlari", "Услуги расчёта заработной платы", "薪酬服务", "Services de paie") },
      { id: "procurement_services", name: row("Procurement Services", "Xarid xizmatlari", "Услуги закупок", "采购服务", "Services d'approvisionnement") },
      { id: "facilities_management", name: row("Facilities Management", "Obyektlarni boshqarish", "Управление объектами", "设施管理", "Gestion des installations") },
      { id: "administrative_services", name: row("Administrative Services", "Maʼmuriy xizmatlar", "Административные услуги", "行政服务", "Services administratifs") },
      { id: "corporate_services", name: row("Corporate Services", "Korporativ xizmatlar", "Корпоративные услуги", "企业服务", "Services aux entreprises") },
      { id: "compliance_services", name: row("Compliance Services", "Muvofiqlik xizmatlari", "Услуги комплаенса", "合规服务", "Services de conformité") },
      { id: "risk_services", name: row("Risk Services", "Xavflarni boshqarish xizmatlari", "Услуги по управлению рисками", "风险服务", "Services de gestion des risques") },
      { id: "outsourcing_technology", name: row("Outsourcing Technology", "Autsorsing texnologiyalari", "Технологии аутсорсинга", "外包技术", "Technologie d'externalisation") },
    ],
  },
  {
    id: "marketing_advertising_and_communications",
    name: row("Marketing, Advertising & Communications", "Marketing, reklama va aloqa", "Маркетинг, реклама и коммуникации", "营销、广告与传播", "Marketing, publicité et communication"),
    subsectors: [
      { id: "advertising", name: row("Advertising", "Reklama", "Реклама", "广告", "Publicité") },
      { id: "digital_advertising", name: row("Digital Advertising", "Raqamli reklama", "Цифровая реклама", "数字广告", "Publicité numérique") },
      { id: "marketing_services", name: row("Marketing Services", "Marketing xizmatlari", "Маркетинговые услуги", "营销服务", "Services de marketing") },
      { id: "marketing_technology", name: row("Marketing Technology", "Marketing texnologiyalari", "Маркетинговые технологии", "营销技术", "Technologie marketing") },
      { id: "public_relations", name: row("Public Relations", "Jamoatchilik bilan aloqalar", "Связи с общественностью", "公共关系", "Relations publiques") },
      { id: "corporate_communications", name: row("Corporate Communications", "Korporativ kommunikatsiyalar", "Корпоративные коммуникации", "企业传播", "Communication d'entreprise") },
      { id: "branding", name: row("Branding", "Brending", "Брендинг", "品牌塑造", "Image de marque") },
      { id: "market_research", name: row("Market Research", "Bozorni tadqiq qilish", "Маркетинговые исследования", "市场调研", "Études de marché") },
      { id: "social_media", name: row("Social Media", "Ijtimoiy tarmoqlar", "Социальные сети", "社交媒体", "Réseaux sociaux") },
      { id: "influencer_and_creator_marketing", name: row("Influencer & Creator Marketing", "Influenser va kontent-meyker marketingi", "Инфлюенсер-маркетинг", "网红与创作者营销", "Marketing d'influence") },
      { id: "content_marketing", name: row("Content Marketing", "Kontent-marketing", "Контент-маркетинг", "内容营销", "Marketing de contenu") },
      { id: "advertising_technology", name: row("Advertising Technology", "Reklama texnologiyalari", "Рекламные технологии", "广告技术", "Technologie publicitaire") },
    ],
  },
  {
    id: "media_entertainment_and_creative_industries",
    name: row("Media, Entertainment & Creative Industries", "Media, koʻngilochar va ijodiy sanoat", "Медиа, развлечения и креативные индустрии", "媒体、娱乐与创意产业", "Médias, divertissement et industries créatives"),
    subsectors: [
      { id: "film_and_television", name: row("Film & Television", "Kino va televideniye", "Кино и телевидение", "电影与电视", "Cinéma et télévision") },
      { id: "music", name: row("Music", "Musiqa", "Музыка", "音乐", "Musique") },
      { id: "publishing", name: row("Publishing", "Nashriyot ishi", "Издательское дело", "出版业", "Édition") },
      { id: "news_and_journalism", name: row("News & Journalism", "Yangiliklar va jurnalistika", "Новости и журналистика", "新闻业", "Actualités et journalisme") },
      { id: "radio", name: row("Radio", "Radio", "Радио", "广播", "Radio") },
      { id: "podcasts", name: row("Podcasts", "Podkastlar", "Подкасты", "播客", "Balados / Podcasts") },
      { id: "streaming", name: row("Streaming", "Strimingi (oqim uzatish)", "Стриминг", "流媒体", "Diffusion en continu") },
      { id: "digital_media", name: row("Digital Media", "Raqamli media", "Цифровые медиа", "数字媒体", "Médias numériques") },
      { id: "gaming", name: row("Gaming", "Video oʻyinlar", "Игровая индустрия", "游戏", "Jeux vidéo") },
      { id: "esports", name: row("Esports", "Kibersport", "Киберспорт", "电子竞技", "Sports électroniques") },
      { id: "animation", name: row("Animation", "Animatsiya", "Анимация", "动画", "Animation") },
      { id: "photography", name: row("Photography", "Fotografiya", "Фотография", "摄影", "Photographie") },
      { id: "design", name: row("Design", "Dizayn", "Дизайн", "设计", "Design") },
      { id: "performing_arts", name: row("Performing Arts", "Sahna sanʼati", "Исполнительское искусство", "表演艺术", "Arts du spectacle") },
      { id: "creative_services", name: row("Creative Services", "Ijodiy xizmatlar", "Креативные услуги", "创意服务", "Services créatifs") },
    ],
  },
  {
    id: "travel_tourism_and_hospitality",
    name: row("Travel, Tourism & Hospitality", "Sayohat, turizm va mehmondoʻstlik", "Путешествия, туризм и гостеприимство", "旅游与酒店业", "Voyage, tourisme et hôtellerie"),
    subsectors: [
      { id: "hotels", name: row("Hotels", "Mehmonxonalar", "Гостиницы", "酒店", "Hôtels") },
      { id: "resorts", name: row("Resorts", "Kurortlar", "Курорты", "度假村", "Complexes touristiques") },
      { id: "accommodation", name: row("Accommodation", "Turar joy xizmatlari", "Средства размещения", "住宿", "Hébergement") },
      { id: "travel_agencies", name: row("Travel Agencies", "Sayohat agentliklari", "Туристические агентства", "旅行社", "Agences de voyage") },
      { id: "tour_operators", name: row("Tour Operators", "Tur-operatorlar", "Туроператоры", "旅游经营商", "Voyagistes") },
      { id: "travel_platforms", name: row("Travel Platforms", "Sayohat platformalari", "Туристические платформы", "旅游平台", "Plateformes de voyage") },
      { id: "airlines", name: row("Airlines", "Aviakompaniyalar", "Авиакомпании", "航空公司", "Compagnies aériennes") },
      { id: "cruises", name: row("Cruises", "Kruiz sayohatlari", "Круизы", "邮轮", "Croisières") },
      { id: "tourism_attractions", name: row("Tourism Attractions", "Turistik diqqatga sazovor joylar", "Туристические достопримечательности", "旅游景点", "Attractions touristiques") },
      { id: "business_travel", name: row("Business Travel", "Ishbilarmonlik sayohatlari", "Деловые поездки", "商务旅行", "Voyages d'affaires") },
      { id: "travel_services", name: row("Travel Services", "Sayohat xizmatlari", "Туристические услуги", "旅游服务", "Services de voyage") },
      { id: "hospitality_technology", name: row("Hospitality Technology", "Mehmondoʻstlik texnologiyalari", "Технологии гостеприимства", "酒店科技", "Technologie hôtelière") },
    ],
  },
  {
    id: "restaurants_catering_and_leisure",
    name: row("Restaurants, Catering & Leisure", "Restoranlar, keytering va dam olish", "Рестораны, кейтеринг и досуг", "餐饮、宴会服务与休闲", "Restaurants, traiteur et loisirs"),
    subsectors: [
      { id: "restaurants", name: row("Restaurants", "Restoranlar", "Рестораны", "餐厅", "Restaurants") },
      { id: "cafes_and_coffee_shops", name: row("Cafes & Coffee Shops", "Kafe va qahvaxonalar", "Кафе и кофейни", "咖啡馆", "Cafés") },
      { id: "catering", name: row("Catering", "Keytering", "Кейтеринг", "宴会餐饮服务", "Traiteur") },
      { id: "food_delivery", name: row("Food Delivery", "Ovqat yetkazib berish", "Доставка еды", "送餐服务", "Livraison de repas") },
      { id: "bars_and_entertainment_venues", name: row("Bars & Entertainment Venues", "Barlar va koʻngilochar maskanlar", "Бары и развлекательные заведения", "酒吧与娱乐场所", "Bars et lieux de divertissement") },
      { id: "leisure_and_recreation", name: row("Leisure & Recreation", "Dam olish va bosh vaqt", "Досуг и отдых", "休闲与娱乐", "Loisirs et récréation") },
      { id: "theme_parks", name: row("Theme Parks", "Ekstremal va tematik parklar", "Тематические парки", "主题公园", "Parcs à thème") },
      { id: "attractions", name: row("Attractions", "Diqqatga sazovor joylar", "Достопримечательности", "景点", "Attractions") },
      { id: "events_and_experiences", name: row("Events & Experiences", "Tadbirlar va tajribalar", "Мероприятия и впечатления", "活动与体验", "Événements et expériences") },
      { id: "leisure_technology", name: row("Leisure Technology", "Dam olish texnologiyalari", "Технологии досуга", "休闲科技", "Technologie des loisirs") },
    ],
  },
  {
    id: "consumer_and_personal_services",
    name: row("Consumer & Personal Services", "Isteʼmolchi va shaxsiy xizmatlar", "Потребительские и персональные услуги", "消费者与个人服务", "Services aux consommateurs et à la personne"),
    subsectors: [
      { id: "beauty_and_personal_care", name: row("Beauty & Personal Care", "Goʻzallik va shaxsiy parvarish", "Красота и личная гигиена", "美容与个人护理", "Beauté et soins personnels") },
      { id: "fitness_and_wellness", name: row("Fitness & Wellness", "Fitnes va salomatlik", "Фитнес и велнес", "健身与养生", "Fitness et bien-être") },
      { id: "home_services", name: row("Home Services", "Uy xizmatlari", "Услуги для дома", "家政服务", "Services à domicile") },
      { id: "cleaning_services", name: row("Cleaning Services", "Tozalash xizmatlari", "Клининговые услуги", "清洁服务", "Services de nettoyage") },
      { id: "repair_and_maintenance_services", name: row("Repair & Maintenance Services", "Taʼmirlash va texnik xizmat koʻrsatish", "Услуги ремонта и обслуживания", "维修与保养服务", "Services de réparation et d'entretien") },
      { id: "laundry_services", name: row("Laundry Services", "Kir yuvish xizmatlari", "Услуги прачечной", "洗衣服务", "Services de blanchisserie") },
      { id: "childcare", name: row("Childcare", "Bolalar parvarishi", "Услуги по уходу за детьми", "儿童看护", "Garde d'enfants") },
      { id: "pet_services", name: row("Pet Services", "Uy hayvonlariga xizmatlar", "Услуги для домашних животных", "宠物服务", "Services pour animaux de compagnie") },
      { id: "personal_coaching", name: row("Personal Coaching", "Shaxsiy kouching", "Персональный коучинг", "私人教练/辅导", "Coaching personnel") },
      { id: "lifestyle_services", name: row("Lifestyle Services", "Turmush tarzi xizmatlari", "Лайфстайл-услуги", "生活方式服务", "Services liés au style de vie") },
      { id: "consumer_service_platforms", name: row("Consumer Service Platforms", "Isteʼmolchi xizmatlari platformalari", "Платформы потребительских услуг", "消费者服务平台", "Plateformes de services aux consommateurs") },
    ],
  },
  {
    id: "sports_and_recreation",
    name: row("Sports & Recreation", "Sport va dam olish", "Спорт и отдых", "体育与休闲", "Sport et loisirs"),
    subsectors: [
      { id: "professional_sports", name: row("Professional Sports", "Professional sport", "Профессиональный спорт", "职业体育", "Sport professionnel") },
      { id: "sports_clubs", name: row("Sports Clubs", "Sport klublari", "Спортивные клубы", "体育俱乐部", "Clubs sportifs") },
      { id: "fitness", name: row("Fitness", "Fitnes", "Фитнес", "健身", "Fitness") },
      { id: "sports_facilities", name: row("Sports Facilities", "Sport inshootlari", "Спортивные сооружения", "体育设施", "Installations sportives") },
      { id: "sports_equipment", name: row("Sports Equipment", "Sport anjomlari", "Спортивный инвентарь", "体育器材", "Équipement sportif") },
      { id: "sports_apparel", name: row("Sports Apparel", "Sport kiyimlari", "Спортивная одежда", "运动服装", "Vêtements de sport") },
      { id: "sports_media", name: row("Sports Media", "Sport mediasi", "Спортивные медиа", "体育媒体", "Médias sportifs") },
      { id: "sports_technology", name: row("Sports Technology", "Sport texnologiyalari", "Спортивные технологии", "体育科技", "Technologie sportive") },
      { id: "sports_analytics", name: row("Sports Analytics", "Sport tahlili", "Спортивная аналитика", "体育数据分析", "Analytique sportive") },
      { id: "sports_management", name: row("Sports Management", "Sportni boshqarish", "Спортивный менеджмент", "体育管理", "Gestion sportive") },
      { id: "recreation", name: row("Recreation", "Dam olish", "Отдых", "休闲娱乐", "Récréation") },
    ],
  },
  {
    id: "fashion_luxury_and_lifestyle",
    name: row("Fashion, Luxury & Lifestyle", "Moda, hashamat va turmush tarzi", "Мода, люкс и лайфстайл", "时尚、奢侈品与生活方式", "Mode, luxe et style de vie"),
    subsectors: [
      { id: "fashion", name: row("Fashion", "Moda", "Мода", "时尚", "Mode") },
      { id: "apparel", name: row("Apparel", "Kiyim-kechak", "Одежда", "服装", "Vêtements") },
      { id: "footwear", name: row("Footwear", "Poyabzal", "Обувь", "鞋类", "Chaussures") },
      { id: "accessories", name: row("Accessories", "Aksessuarlar", "Аксессуары", "配饰", "Accessoires") },
      { id: "jewelry", name: row("Jewelry", "Zargarlik buyumlari", "Ювелирные изделия", "珠宝", "Bijouterie") },
      { id: "luxury_goods", name: row("Luxury Goods", "Hashamatli tovarlar", "Люксовые товары", "奢侈品", "Biens de luxe") },
      { id: "beauty_and_cosmetics", name: row("Beauty & Cosmetics", "Goʻzallik va kosmetika", "Красота и косметика", "美妆", "Beauté et cosmétiques") },
      { id: "home_and_lifestyle", name: row("Home & Lifestyle", "Uy va turmush tarzi", "Дом и лайфстайл", "家居与生活方式", "Maison et style de vie") },
      { id: "luxury_services", name: row("Luxury Services", "Hashamatli xizmatlar", "Люксовые услуги", "奢侈品服务", "Services de luxe") },
      { id: "fashion_technology", name: row("Fashion Technology", "Moda texnologiyalari", "Модные технологии", "时尚科技", "Technologie de la mode") },
    ],
  },
  {
    id: "environmental_and_climate_economy",
    name: row("Environmental & Climate Economy", "Ekologik va iqlim iqtisodiyoti", "Экологическая и климатическая экономика", "环境与气候经济", "Économie environnementale et climatique"),
    subsectors: [
      { id: "environmental_services", name: row("Environmental Services", "Ekologik xizmatlar", "Экологические услуги", "环境服务", "Services environnementaux") },
      { id: "climate_technology", name: row("Climate Technology", "Iqlim texnologiyalari", "Климатические технологии", "气候科技", "Technologie climatique") },
      { id: "carbon_management", name: row("Carbon Management", "Uglerodni boshqarish", "Управление углеродом", "碳管理", "Gestion du carbone") },
      { id: "carbon_markets", name: row("Carbon Markets", "Uglerod bozorlari", "Углеродные рынки", "碳市场", "Marchés du carbone") },
      { id: "carbon_capture_and_removal", name: row("Carbon Capture & Removal", "Uglerodni ushlab qolish va olib tashlash", "Улавливание и удаление углерода", "碳捕集与去除", "Captage et élimination du carbone") },
      { id: "circular_economy", name: row("Circular Economy", "Aylanma iqtisodiyot", "Циркулярная экономика", "循环经济", "Économie circulaire") },
      { id: "recycling_technology", name: row("Recycling Technology", "Qayta ishlash texnologiyalari", "Технологии переработки", "回收技术", "Technologie de recyclage") },
      { id: "sustainable_materials", name: row("Sustainable Materials", "Barqaror materiallar", "Устойчивые материалы", "可持续材料", "Matériaux durables") },
      { id: "environmental_monitoring", name: row("Environmental Monitoring", "Ekologik monitoring", "Экологический мониторинг", "环境监测", "Surveillance environnementale") },
      { id: "climate_risk_and_analytics", name: row("Climate Risk & Analytics", "Iqlim xavfi va tahlili", "Климатические риски и аналитика", "气候风险与分析", "Risques climatiques et analytique") },
      { id: "sustainable_agriculture", name: row("Sustainable Agriculture", "Barqaror qishloq xoʻjaligi", "Устойчивое сельское хозяйство", "可持续农业", "Agriculture durable") },
      { id: "sustainability_services", name: row("Sustainability Services", "Barqarorlik xizmatlari", "Услуги в области устойчивого развития", "可持续发展服务", "Services de développement durable") },
    ],
  },
  {
    id: "water_and_water_technology",
    name: row("Water & Water Technology", "Suv va suv texnologiyalari", "Вода и водные технологии", "水与水技术", "Eau et technologies de l'eau"),
    subsectors: [
      { id: "water_supply", name: row("Water Supply", "Suv taʼminoti", "Водоснабжение", "供水", "Approvisionnement en eau") },
      { id: "water_treatment", name: row("Water Treatment", "Suvni tozalash", "Водоочистка", "水处理", "Traitement de l'eau") },
      { id: "wastewater_treatment", name: row("Wastewater Treatment", "Oqova suvlarni tozalash", "Очистка сточных вод", "污水处理", "Traitement des eaux usées") },
      { id: "desalination", name: row("Desalination", "Suvni chuchuklashtirish", "Опреснение", "海水淡化", "Dessalement") },
      { id: "water_infrastructure", name: row("Water Infrastructure", "Suv infratuzilmasi", "Водная инфраструктура", "水利基础设施", "Infrastructures hydrauliques") },
      { id: "irrigation", name: row("Irrigation", "Sugʻorish", "Ирригация", "灌溉", "Irrigation") },
      { id: "industrial_water", name: row("Industrial Water", "Sanoat suvi", "Промышленное водоснабжение", "工业用水", "Eau industrielle") },
      { id: "water_monitoring", name: row("Water Monitoring", "Suv monitoringi", "Мониторинг воды", "水质监测", "Surveillance de l'eau") },
      { id: "water_efficiency", name: row("Water Efficiency", "Suvdan samarali foydalanish", "Водоэффективность", "节水", "Efficacité de l'eau") },
      { id: "water_technology", name: row("Water Technology", "Suv texnologiyalari", "Водные технологии", "水技术", "Technologie de l'eau") },
    ],
  },
  {
    id: "aerospace_and_space",
    name: row("Aerospace & Space", "Aerokosmik va kosmik sanoat", "Авиакосмическая и космическая отрасль", "航空航天与太空", "Aérospatiale et spatial"),
    subsectors: [
      { id: "aerospace_manufacturing", name: row("Aerospace Manufacturing", "Aerokosmik ishlab chiqarish", "Авиакосмическое производство", "航空航天制造", "Fabrication aérospatiale") },
      { id: "aviation_technology", name: row("Aviation Technology", "Aviatsiya texnologiyalari", "Авиационные технологии", "航空技术", "Technologie aéronautique") },
      { id: "space_launch", name: row("Space Launch", "Kosmosga uchirish", "Космические запуски", "太空发射", "Lancement spatial") },
      { id: "satellites", name: row("Satellites", "Sunʼiy yoʻldoshlar", "Спутники", "卫星", "Satellites") },
      { id: "satellite_communications", name: row("Satellite Communications", "Sputnik aloqasi", "Спутниковая связь", "卫星通信", "Communications par satellite") },
      { id: "earth_observation", name: row("Earth Observation", "Yerni masofadan zondlash", "Дистанционное зондирование Земли", "地球观测", "Observation de la Terre") },
      { id: "space_data", name: row("Space Data", "Kosmik maʼlumotlar", "Космические данные", "太空数据", "Données spatiales") },
      { id: "space_infrastructure", name: row("Space Infrastructure", "Kosmik infratuzilma", "Космическая инфраструктура", "太空基础设施", "Infrastructures spatiales") },
      { id: "space_robotics", name: row("Space Robotics", "Kosmik robototexnika", "Космическая робототехника", "太空机器人", "Robotique spatiale") },
      { id: "space_manufacturing", name: row("Space Manufacturing", "Kosmosda ishlab chiqarish", "Космическое производство", "太空制造", "Fabrication spatiale") },
      { id: "space_services", name: row("Space Services", "Kosmik xizmatlar", "Космические услуги", "太空服务", "Services spatiaux") },
      { id: "space_tourism", name: row("Space Tourism", "Kosmik turizm", "Космический туризм", "太空旅游", "Tourisme spatial") },
    ],
  },
  {
    id: "defense_and_security",
    name: row("Defense & Security", "Mudofaa va xavfsizlik", "Оборона и безопасность", "国防与安全", "Défense et sécurité"),
    subsectors: [
      { id: "defense_manufacturing", name: row("Defense Manufacturing", "Mudofaa sanoati ishlab chiqarishi", "Производство оборонной продукции", "国防制造", "Fabrication de défense") },
      { id: "defense_technology", name: row("Defense Technology", "Mudofaa texnologiyalari", "Оборонные технологии", "国防技术", "Technologie de défense") },
      { id: "military_aerospace", name: row("Military Aerospace", "Harbiy aerokosmik sanoat", "Военно-космическая отрасль", "军用航空航天", "Aérospatiale militaire") },
      { id: "naval_and_maritime_defense", name: row("Naval & Maritime Defense", "Harbiy-dengiz mudofaasi", "Военно-морская оборона", "海军与海上防务", "Défense navale et maritime") },
      { id: "defense_electronics", name: row("Defense Electronics", "Mudofaa elektronikasi", "Оборонная электроника", "国防电子", "Électronique de défense") },
      { id: "defense_software", name: row("Defense Software", "Mudofaa dasturiy taʼminoti", "Оборонное ПО", "国防软件", "Logiciels de défense") },
      { id: "cyber_defense", name: row("Cyber Defense", "Kiber mudofaa", "Киберзащита", "网络防御", "Cyberdéfense") },
      { id: "intelligence_technology", name: row("Intelligence Technology", "Razvedka texnologiyalari", "Разведывательные технологии", "情报技术", "Technologie du renseignement") },
      { id: "security_technology", name: row("Security Technology", "Xavfsizlik texnologiyalari", "Технологии безопасности", "安防技术", "Technologie de sécurité") },
      { id: "physical_security", name: row("Physical Security", "Jismoniy xavfsizlik", "Физическая безопасность", "实体安防", "Sécurité physique") },
      { id: "defense_services", name: row("Defense Services", "Mudofaa xizmatlari", "Оборонные услуги", "国防服务", "Services de défense") },
    ],
  },
  {
    id: "government_and_public_services",
    name: row("Government & Public Services", "Davlat va davlat xizmatlari", "Государственное управление и государственные услуги", "政府与公共服务", "Administration et services publics"),
    subsectors: [
      { id: "public_administration", name: row("Public Administration", "Davlat boshqaruvi", "Государственное управление", "公共行政", "Administration publique") },
      { id: "government_services", name: row("Government Services", "Davlat xizmatlari", "Государственные услуги", "政府服务", "Services gouvernementaux") },
      { id: "public_finance", name: row("Public Finance", "Davlat moliyasi", "Государственные финансы", "公共财政", "Finances publiques") },
      { id: "public_infrastructure", name: row("Public Infrastructure", "Davlat infratuzilmasi", "Государственная инфраструктура", "公共基础设施", "Infrastructures publiques") },
      { id: "public_healthcare", name: row("Public Healthcare", "Davlat sogʻliqni saqlash tizimi", "Государственное здравоохранение", "公共医疗", "Santé publique") },
      { id: "public_education", name: row("Public Education", "Davlat taʼlim tizimi", "Государственное образование", "公共教育", "Éducation publique") },
      { id: "social_services", name: row("Social Services", "Ijtimoiy xizmatlar", "Социальные услуги", "社会服务", "Services sociaux") },
      { id: "public_transportation", name: row("Public Transportation", "Jamoat transporti", "Общественный транспорт", "公共交通", "Transport public") },
      { id: "emergency_services", name: row("Emergency Services", "Favqulodda vaziyatlar xizmati", "Экстренные службы", "应急服务", "Services d'urgence") },
      { id: "government_technology", name: row("Government Technology", "Davlat texnologiyalari (GovTech)", "Государственные технологии (GovTech)", "政务科技", "Technologie gouvernementale") },
      { id: "civic_technology", name: row("Civic Technology", "Fuqarolik texnologiyalari", "Гражданские технологии", "公民科技", "Technologie civique") },
    ],
  },
  {
    id: "social_economy_and_nonprofit_sector",
    name: row("Social Economy & Nonprofit Sector", "Ijtimoiy iqtisodiyot va notijorat sektor", "Социальная экономика и некоммерческий сектор", "社会经济与非营利部门", "Économie sociale et secteur à but non lucratif"),
    subsectors: [
      { id: "nonprofit_organizations", name: row("Nonprofit Organizations", "Notijorat tashkilotlar", "Некоммерческие организации", "非营利组织", "Organisations à but non lucratif") },
      { id: "charities_and_foundations", name: row("Charities & Foundations", "Xayriya tashkilotlari va jamgʻarmalar", "Благотворительные организации и фонды", "慈善机构与基金会", "Organismes caritatifs et fondations") },
      { id: "social_enterprises", name: row("Social Enterprises", "Ijtimoiy tadbirkorlik korxonalari", "Социальные предприятия", "社会企业", "Entreprises sociales") },
      { id: "community_services", name: row("Community Services", "Jamoat xizmatlari", "Общественные услуги", "社区服务", "Services communautaires") },
      { id: "development_organizations", name: row("Development Organizations", "Rivojlanish tashkilotlari", "Организации развития", "发展组织", "Organisations de développement") },
      { id: "microfinance_and_financial_inclusion", name: row("Microfinance & Financial Inclusion", "Mikromoliyalash va moliyaviy inklyuziya", "Микрофинансирование и финансовая доступность", "小额信贷与普惠金融", "Microfinance et inclusion financière") },
      { id: "social_impact_services", name: row("Social Impact Services", "Ijtimoiy taʼsir xizmatlari", "Услуги социального воздействия", "社会影响力服务", "Services d'impact social") },
      { id: "humanitarian_services", name: row("Humanitarian Services", "Insonparvarlik xizmatlari", "Гуманитарные услуги", "人道主义服务", "Services humanitaires") },
    ],
  },
  {
    id: "emerging_and_frontier_technology",
    name: row("Emerging & Frontier Technology", "Yangi paydo boʻlayotgan va ilgʻor texnologiyalar", "Новейшие и передовые технологии", "新兴与前沿技术", "Technologies émergentes et de pointe"),
    subsectors: [
      { id: "quantum_computing", name: row("Quantum Computing", "Kvant hisoblash", "Квантовые вычисления", "量子计算", "Informatique quantique") },
      { id: "quantum_technology", name: row("Quantum Technology", "Kvant texnologiyalari", "Квантовые технологии", "量子技术", "Technologie quantique") },
      { id: "advanced_materials", name: row("Advanced Materials", "Ilgʻor materiallar", "Передовые материалы", "先进材料", "Matériaux avancés") },
      { id: "nanotechnology", name: row("Nanotechnology", "Nanotexnologiya", "Нанотехнологии", "纳米技术", "Nanotechnologie") },
      { id: "photonics", name: row("Photonics", "Fotonika", "Фотоника", "光子学", "Photonique") },
      { id: "neurotechnology", name: row("Neurotechnology", "Nevrotexnologiya", "Нейротехнологии", "神经科技", "Neurotechnologie") },
      { id: "brain_computer_interfaces", name: row("Brain-Computer Interfaces", "Miya-kompyuter interfeyslari", "Нейрокомпьютерные интерфейсы", "脑机接口", "Interfaces cerveau-machine") },
      { id: "fusion_technology", name: row("Fusion Technology", "Termoyadro texnologiyalari", "Термоядерные технологии", "聚变技术", "Technologie de fusion") },
      { id: "advanced_nuclear_technology", name: row("Advanced Nuclear Technology", "Ilgʻor yadro texnologiyalari", "Передовые ядерные технологии", "先进核技术", "Technologie nucléaire avancée") },
      { id: "synthetic_biology", name: row("Synthetic Biology", "Sintetik biologiya", "Синтетическая биология", "合成生物学", "Biologie synthétique") },
      { id: "deep_technology", name: row("Deep Technology", "Chuqur texnologiyalar (Deep Tech)", "Глубокие технологии (Deep Tech)", "深科技", "Technologie de rupture (Deep Tech)") },
      { id: "frontier_technology", name: row("Frontier Technology", "Ilgʻor chegara texnologiyalari", "Передовые технологии", "前沿技术", "Technologie de pointe") },
    ],
  },
];

export function findSectorGroup(groupId: string): SectorGroup | undefined {
  return SECTOR_TAXONOMY.find((g) => g.id === groupId);
}
export function findSubSector(groupId: string, subId: string): SubSector | undefined {
  return findSectorGroup(groupId)?.subsectors.find((s) => s.id === subId);
}
// English canonical combined label — this is what gets stored (Business.sector
// stays a plain, untranslated string, same as the original free-text field did).
export function sectorDisplayLabel(groupId: string, subId: string): string {
  const group = findSectorGroup(groupId);
  const sub = findSubSector(groupId, subId);
  if (!group || !sub) return "";
  return `${group.name.en} — ${sub.name.en}`;
}
